### PR TITLE
Create wrapperElement to tag

### PR DESCRIPTION
**Pull request by quexpl**
Hi, i've added wrapper around button, and moved popup to wrapper outside buttonElement. I needed this because i have anchor in popup and it was unaccessible when it was in buttonElement. 
What do you think about this change?

### CODE REVIEW

**Comment by timseverien** [comment]
Thanks for your contribution! This is how I built it initially, but I experienced some issues.

If you open a popup, the wrapper enlarges. If the wrapper overlaps another button, that button cannot be clicked. This is extremely annoying if configure Taggd to toggle the popups on click, which allows you to open several simultaneously. This _can_ be fixed using `pointer-events: none`, but isn't well supported: http://caniuse.com/#feat=pointer.

To support your use-case without breaking it for others, we'll have to get rid of the wrapper and keep the button and popup on the same DOM level. Is that something you are willing to do? I will be ever so grateful if you do.

**Comment by quexpl** [comment]
If we set position: absolute to taggd__popup, then it won't enlarge taggd_wrapper. 
I have checked editor.html from master and my branch, with one change - events was trigged by click. In master textfield, is unreachable but you can click on other buttons. In version from my branch, you can use elements inside taggd__popup, and other buttons are clickable. This is posible becouse taggd__popup in taggd-classic.css has position: absolute; 

Maybe this is solution?

**Comment by timseverien** [comment]
Good point. I'll test that thoroughly tonight :)

**Comment by timseverien** [comment]
Tested it, fixed a bug, and merged it :)

Thanks a lot for the help!

**Pull request merged**
